#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 - 2025 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense
#
# See the output of "$0 -h" for details.

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
#set -Eeu

script_path="$(readlink -f "${BASH_SOURCE[0]}")"
script_dir="$(dirname "$script_path")"
script_name="$(basename "$script_path")"

proj_root_dir="$(dirname "$script_dir")"
suppl_dir="$proj_root_dir/supplements"
img_dir="$proj_root_dir/image"
suppl_git_ssh_url="ssh://git@codeberg.org/FairIT/assembly-kit-supplements.git"

function print_help() {

	echo "$script_name - Fetches the latest version"
	echo "of the supplements repo associated to with this repo,"
	echo "and then converts the original images therein to a smaller size,"
	echo "and stores them in this repo."
	echo
	echo "Usage:"
	echo "  $script_name [OPTION...]"
	echo "Options:"
	echo "  -h, --help"
	echo "    Show this help message and exit"
	echo "Examples:"
	echo "  $script_name"
	echo "  $script_name --help"
}

# Process command line arguments
while [[ $# -gt 0 ]]
do
	arg="$1"
	shift # $2 -> $1, $3 -> $2, ...

	case "$arg" in
		-h|--help)
			print_help
			exit 0
			;;
		*) # non-/unknown option
			>&2 echo "ERROR: Unknown flag: '$arg'"
			exit 1
			;;
	esac
done

echo "INFO: Fetching the latest version of the supplements repo ..."
if ! [ -e "$suppl_dir" ]
then
	git clone "$suppl_git_ssh_url" "$suppl_dir"
else
	git -C "$suppl_dir" pull
fi
echo "INFO: Fetching the latest version of the supplements repo - done."
echo

echo "INFO: We check if this repo is clean,"
echo "INFO: so we do not accidentally overwrite uncommitted changes to images."
echo

echo "INFO: Checking repo state ..."
status="$(git status -u --porcelain)"
echo "INFO: Checking repo state - done."
if [ -z "$status" ]
then
	echo "INFO: No local, uncommitted changes -> We are good to go."
else
	>&2 echo "WARN: The local workspace is modified -> aborting."
	echo "INFO: Commit or revert all changes before running this script."
	exit 2
fi
echo

# CROP_DIMENSIONS="800x600"
CROP_DIMENSIONS="1024x768"
# NEW_EXT="png"
NEW_EXT="jpg"
# MAX_SIZE="300kb"

mkdir -p "$img_dir"

echo "INFO: Converting images to smaller versions ..."
for orig_img_path in "$suppl_dir/image/"*.{png,jpg}
do
	file_name="$(basename -- "$orig_img_path")"
	echo "INFO: Converting image '$file_name' ..."
	# orig_extension="${file_name##*.}"
	file_name_no_ext="${file_name%.*}"
	new_img_path="$img_dir/$file_name_no_ext.$NEW_EXT"
	convert \
		-filter "Lanczos" \
		-quality 85 \
		-resize "${CROP_DIMENSIONS}>" \
		"$orig_img_path" \
		"$new_img_path"
#		-scale "50%" \
#		-define jpeg:extent="$MAX_SIZE" \
		# -thumbnail "$NEW_WIDTH" \
	echo "INFO: Converting image '$file_name' - done."
done
echo "INFO: Converting images to smaller versions - done."
echo

echo "done."